server:
  port: 80 #配置服务器端口
spring:
  thymeleaf:
    cache: false  #模板缓存
    check-template-location: true #检查模板文件夹是否存在
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: LEGACYHTML5 #指定模板视图为LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: jdbc:mysql://localhost:3306/malaria?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: 1223
    driver-class-name: com.mysql.jdbc.Driver
  cache:
    ehcache:
      config: cacheCfg/dev.xml #配置缓存管理文件
mybatis:
  configuration:
    cache-enabled: true #开启缓存
    map-underscore-to-camel-case: true #开启驼峰命名
    lazy-loading-enabled: true #全局懒加载配置
    default-statement-timeout: 3000 #语句查询超时时间
    default-executor-type: simple #配置和设置执行器
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #sql语句输出到控制台配置
  mapper-locations: classpath*:mapper/*/*.xml
  type-aliases-package: com.edupractice.malaria.modules.*.pojo
debug: true


